# -*- coding: utf-8 -*-
"""Conditional statement

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eM0TrNYFD3Kqsa0MptjrilG1Phc_3fYg
"""



print(5==5)
print(5==4)
print(5!=5)
print(5!=4)
print(5>6)
print(5<7)
print(5>=4)

age=input("How old are you ")
#changing string to interger-comment
age=int(age)
if age>=18:
  print("you are viable to vote")
else:
  print("you are under age")

print("trafficlight")
trafficlight=input("enter either red yellow or green")
if trafficlight=="red":
  print("stop")
elif trafficlight=="yellow":
  print("slow down")
elif trafficlight=="green":
  print("go")
else:
  print("check the spelling")

print("creat my account")
#user input
username=input("create user name ")
dob=input("Year of birth")
dob=int(dob)
email=input("enter your email")
pw=input("create your password ")
age=2026-dob
if age>=18:
  print("you are eligible to create the account")
  print(f"welcome {username} your email is {email}")
else:
  print(f"sorry {username} you are only {age} old ")

print("login to your account")
loginname=input("enter your account name")
loginpw=input("enter your account password")
if loginname==username and loginpw==pw:
  print(f"welcome back{username}")
else:
  print("wrong password or user name ")